// <auto-generated />
using System;
using EfCoreEncapsulation.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfCoreEncapsulation.Api.Migrations
{
    [DbContext(typeof(GymContext))]
    [Migration("20240805192557_Add_Seed_Data_To_Tables")]
    partial class Add_Seed_Data_To_Tables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EfCoreEncapsulation.Api.Classes.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClassId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("ClassId");

                    b.ToTable("Classes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassName = "Yoga",
                            Instructor = "Alice Johnson"
                        },
                        new
                        {
                            Id = 2,
                            ClassName = "Pilates",
                            Instructor = "Bob Brown"
                        },
                        new
                        {
                            Id = 3,
                            ClassName = "Cycling",
                            Instructor = "Leslie Cabrera"
                        });
                });

            modelBuilder.Entity("EfCoreEncapsulation.Api.Enrollments.Enrollment", b =>
                {
                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("FK_Enrollments_Classes_ClassId")
                        .HasColumnType("int");

                    b.Property<int>("FK_Enrollments_Members_MemberId")
                        .HasColumnType("int");

                    b.HasKey("MemberId", "ClassId")
                        .HasName("PK_Enrollments");

                    b.HasIndex("FK_Enrollments_Classes_ClassId");

                    b.HasIndex("FK_Enrollments_Members_MemberId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("EfCoreEncapsulation.Api.Members.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"), 1L, 1);

                    b.Property<DateTime>("MembershipStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("MemberId")
                        .HasName("PK_Members");

                    b.ToTable("Members", (string)null);

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            MembershipStartDate = new DateTime(2024, 8, 5, 15, 25, 57, 666, DateTimeKind.Local).AddTicks(409),
                            Name = "John Doe"
                        },
                        new
                        {
                            MemberId = 2,
                            MembershipStartDate = new DateTime(2024, 8, 5, 15, 25, 57, 666, DateTimeKind.Local).AddTicks(442),
                            Name = "Jane Smith"
                        },
                        new
                        {
                            MemberId = 3,
                            MembershipStartDate = new DateTime(2024, 8, 5, 15, 25, 57, 666, DateTimeKind.Local).AddTicks(443),
                            Name = "Paige Patchet"
                        });
                });

            modelBuilder.Entity("EfCoreEncapsulation.Api.Enrollments.Enrollment", b =>
                {
                    b.HasOne("EfCoreEncapsulation.Api.Classes.Class", "Class")
                        .WithMany("Enrollments")
                        .HasForeignKey("FK_Enrollments_Classes_ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EfCoreEncapsulation.Api.Members.Member", "Member")
                        .WithMany("Enrollments")
                        .HasForeignKey("FK_Enrollments_Members_MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("EfCoreEncapsulation.Api.Classes.Class", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("EfCoreEncapsulation.Api.Members.Member", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
