// <auto-generated />
using System;
using EfCoreEncapsulation.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfCoreEncapsulation.Api.Migrations
{
    [DbContext(typeof(GymContext))]
    [Migration("20240804230857_Added-Data-To-Tables")]
    partial class AddedDataToTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EfCoreEncapsulation.Api.Classes.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"), 1L, 1);

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassId = 1,
                            ClassName = "Yoga",
                            Instructor = "Alice Johnson"
                        },
                        new
                        {
                            ClassId = 2,
                            ClassName = "Pilates",
                            Instructor = "Bob Brown"
                        });
                });

            modelBuilder.Entity("EfCoreEncapsulation.Api.Enrollments.Enrollment", b =>
                {
                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.HasKey("MemberId", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            ClassId = 1
                        },
                        new
                        {
                            MemberId = 2,
                            ClassId = 2
                        });
                });

            modelBuilder.Entity("EfCoreEncapsulation.Api.Members.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"), 1L, 1);

                    b.Property<DateTime>("MembershipStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            MembershipStartDate = new DateTime(2024, 8, 4, 19, 8, 57, 222, DateTimeKind.Local).AddTicks(4915),
                            Name = "John Doe"
                        },
                        new
                        {
                            MemberId = 2,
                            MembershipStartDate = new DateTime(2024, 8, 4, 19, 8, 57, 222, DateTimeKind.Local).AddTicks(4945),
                            Name = "Jane Smith"
                        });
                });

            modelBuilder.Entity("EfCoreEncapsulation.Api.Enrollments.Enrollment", b =>
                {
                    b.HasOne("EfCoreEncapsulation.Api.Classes.Class", "Class")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EfCoreEncapsulation.Api.Members.Member", "Member")
                        .WithMany("Enrollments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("EfCoreEncapsulation.Api.Classes.Class", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("EfCoreEncapsulation.Api.Members.Member", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
